project_id = "jqhmxrzzqzlwongbrdio"

[db]
shadow_database_url = "postgresql://postgres:postgres@127.0.0.1:54322/postgres"

[auth]
site_url = "http://localhost:3000"
additional_redirect_urls = ["http://localhost:3000/auth/callback"]
